-- 코드를 입력하세요
SELECT 
    A.MEMBER_NAME, 
    B.REVIEW_TEXT, 
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE A,
    REST_REVIEW B,
    (
    SELECT
        DISTINCT X.MEMBER_ID
        ,COUNT(X.REVIEW_ID)
        OVER(PARTITION BY X.MEMBER_ID) AS CNT_RV
    FROM 
        REST_REVIEW X
    ORDER BY CNT_RV DESC
    limit 1
        ) C
WHERE 
    A.MEMBER_ID = B.MEMBER_ID
    AND
    B.MEMBER_ID = C.MEMBER_ID
ORDER BY 
    REVIEW_DATE ASC,
    REVIEW_TEXT ASC;